### ISSUE TITLE
jekyll doctor crashes with octopress-hooks

### ISSUE THREAD

**Issue by tkrotoff** [octopress/hooks#12]
```
$ bundle exec jekyll doctor --trace
Configuration file: /Users/tanguy/osteo15.com/_config.yml
/Users/tanguy/osteo15.com/vendor/bundle/ruby/2.0.0/gems/octopress-hooks-2.6.0/lib/octopress-hooks.rb:177:in `read': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/tanguy/osteo15.com/vendor/bundle/ruby/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/doctor.rb:22:in `process'
	from /Users/tanguy/osteo15.com/vendor/bundle/ruby/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/doctor.rb:15:in `block (2 levels) in init_with_program'
	from /Users/tanguy/osteo15.com/vendor/bundle/ruby/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/tanguy/osteo15.com/vendor/bundle/ruby/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/tanguy/osteo15.com/vendor/bundle/ruby/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/tanguy/osteo15.com/vendor/bundle/ruby/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/tanguy/osteo15.com/vendor/bundle/ruby/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/tanguy/osteo15.com/vendor/bundle/ruby/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/tanguy/osteo15.com/vendor/bundle/ruby/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /Users/tanguy/osteo15.com/vendor/bundle/ruby/2.0.0/bin/jekyll:23:in `load'
	from /Users/tanguy/osteo15.com/vendor/bundle/ruby/2.0.0/bin/jekyll:23:in `<main>'
```

If I remove `octopress-minify-html` (which depends on `octopress-hooks`) from my Gemfile and _config.yml => no `jekyll doctor` crash.

(Here the website source code if needed: https://github.com/tkrotoff/osteo15.com)

**Comment by imathis** [comment]
Eep. I'll see what I can do to fix this. Thanks for the report!
