### ISSUE TITLE
TypeError when using octopress-hooks on a site with collections

### ISSUE THREAD

**Issue by gntech** [octopress/hooks#13]
I have found a bug in octopress-hooks and the way to reproduce it on jekyll new site is the following.

Gemfile:
```
source 'https://rubygems.org'

gem 'jekyll', '3.0.0.pre.beta8'

group :jekyll_plugins do
  gem "octopress-hooks"
end
```

Create the collection and a test file in it.
```
mkdir _projects
echo "---\nlayout: page\ntitle: test\n---" > _projects/test.md
```

_config.yml
```
collections:
- projects
```

This yields the following error when building
```
$ jekyll b -t    
Configuration file: /home/gustav/git/pag-trouble/_config.yml
            Source: /home/gustav/git/pag-trouble
       Destination: /home/gustav/git/pag-trouble/_site
 Incremental build: enabled
      Generating... 
  Liquid Exception: no implicit conversion of nil into String in _projects/test.md
/home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll.rb:159:in `expand_path': no implicit conversion of nil into String (TypeError)
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll.rb:159:in `sanitized_path'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:371:in `block in in_source_dir'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:370:in `each'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:370:in `reduce'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:370:in `in_source_dir'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/liquid_renderer.rb:16:in `file'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/renderer.rb:95:in `render_liquid'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:311:in `render_liquid'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/renderer.rb:52:in `run'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:306:in `run'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:172:in `block (2 levels) in render'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:170:in `each'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:170:in `block in render'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:169:in `each'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:169:in `render'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:197:in `render'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:59:in `process'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/command.rb:28:in `process_site'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/commands/build.rb:60:in `build'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/commands/build.rb:35:in `process'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/bin/jekyll:17:in `<top (required)>'
	from /home/gustav/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `load'
	from /home/gustav/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `<main>'
	from /home/gustav/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/gustav/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by gntech** [comment]
Interesting enough, this error does not appear when using jekyll 3.0.0.pre.beta7

**Comment by Frozenfire92** [comment]
Did you ever get this sorted out? I think I have the same issue https://github.com/octopress/paginate/issues/18

**Comment by gntech** [comment]
No unfortunately not, I never managed to find the culprit to that problem. But it worked on jekyll 3.0.0.pre.beta7 so something probably happened between beta7 and beta8.

**Comment by parkr** [comment]
Octopress Hooks was supplanted by Jekyll's native hooks.

**Comment by Frozenfire92** [comment]
@parkr can you look into octopress/paginate#18 or ping the maintainer. It seems I'm not the only one with the issue and someone else provided other ways to reproduce

**Comment by parkr** [comment]
Fixed on `master`.
